matrix:
  include:
    - os: windows
      language: rust
      env:
        - TOOLCHAIN=MinGW
      rust:
        - nightly

    - os: windows
      language: rust
      rust:
        - stable
      before_script:
        - choco install visualstudio2019community
        - choco install visualstudio2019-workload-nativedesktop
        - export VS160COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools"
        - rustup toolchain install stable-x86_64-pc-windows-msvc
        - rustup default stable-msvc

    - os: windows
      language: rust
      rust:
        - nightly
      before_script:
        - choco install visualstudio2019community
        - choco install visualstudio2019-workload-nativedesktop
        - export VS160COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/Tools"
        - rustup toolchain install nightly-x86_64-pc-windows-msvc
        - rustup default nightly-msvc

    - os: linux
      dist: bionic
      language: rust
      rust:
        - stable
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9

    - os: linux
      dist: bionic
      language: rust
      rust:
          - nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
      env:
        - CC=gcc-10
        - CXX=g++-10

    - os: linux
      dist: bionic
      arch: arm64
      language: rust
      rust:
        - stable

    - os: linux
      dist: bionic
      arch: arm64
      language: rust
      rust:
        - nightly

    - os: osx
      osx_image: xcode12
      language: rust
      rust:
        - stable

    - os: osx
      osx_image: xcode12
      language: rust
      rust:
        - nightly
  allow_failures:
    env: TOOLCHAIN=MinGW
        
cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    
script:
  - cargo test --all
  - cargo test --all --features 1mib
  - cargo test --all --features build_cc
  - cargo test --all --features debug
  - cargo test --all --features cache-friendly



