[package]
name = "snmalloc-rs"
version = "0.1.0"
authors = ["schrodingerzhu <i@zhuyi.fan>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snmalloc-sys = {path = "snmalloc-sys"}

[features]
1mib = ["snmalloc-sys/1mib"]
debug = ["snmalloc-sys/debug"]
cache-friendly = ["snmalloc-sys/cache-friendly"]