[package]
name = "snmalloc-sys"
version = "0.1.0"
authors = ["schrodingerzhu <i@zhuyi.fan>"]
edition = "2018"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cmake = "0.1"

[dependencies.libc]
version = "*"
default-features = false

[features]
1mib = []
debug = []
cache-friendly = []